### ISSUE TITLE
Incorrect -t -e values can lead to core dump

### ISSUE THREAD

**Issue by twekkel** [flanglet/kanzi-cpp#10]
**okay**
$ ./kanzi -c -t empty -e tpaqx -i in -f -v 0
Could not create the compressor: Unknown transform type: 'EMPTY'

$ ./kanzi -c -t none -e tpaqx -i in -f -v 0

**not okay**
$ ./kanzi -c -t '' -e tpaqx -i in -f -v 0
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 1) > this->size() (which is 0)
Aborted (core dumped)

$ ./kanzi -c -t none -e '' -i in -f -v 0
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 1) > this->size() (which is 0)
Aborted (core dumped)

**Comment by flanglet** [comment]
Good catch. Should be easy to fix.

**Comment by flanglet** [comment]
Commit [8aed7a11]
