### ISSUE TITLE
Kanzi 2.1 command line tool crashes upon use

### ISSUE THREAD

**Issue by Bits360** [flanglet/kanzi-cpp#11]
2.1 when entering any command (including -h) crashes with a "The application was unable to start correctly (0xc000007b) Click OK to close the application."
2.0 works as expected.

**Comment by flanglet** [comment]
I do not see that on my hand. What is you environment (OS, compiler, etc...) ? Have you tried to clean all obejcts before rebuilding.

**Comment by Bits360** [comment]
Windows 10 latest, Whatever compiler your using, as im using the prebuilt version.

**Comment by flanglet** [comment]
Release updated with VC built binary.
