### ISSUE TITLE
Feature request: install target

### ISSUE THREAD

**Issue by data-man** [flanglet/kanzi-cpp#12]
The great project, thank you!

I want to use Kanzi as an embedded compressor, with static linking.

**Comment by flanglet** [comment]
Target added. Give it a try.

**Comment by data-man** [comment]
Thank you!
What about headers? E.g. install them to `/usr/local/kanzi`.

**Comment by flanglet** [comment]
Good point. I added the headers. You are the first to test this config..,

**Comment by data-man** [comment]
Thank you!
I think the uninstall target can also be useful. Many developers forget it.

**Comment by flanglet** [comment]
If you install Kanzi, it is forever !
Just kidding, I added an uninstall target.

**Comment by data-man** [comment]
Many thanks, solved!
