### ISSUE TITLE
i can't build binary in MSVC2022

### ISSUE THREAD

**Issue by check4game** [flanglet/kanzi-cpp#13]
Hi

62 errors in project
`libapi.cpp

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\utility(655,42): error C2440: '=': cannot convert from '_Other' to '_Ty'
          with
          [
              _Other=int
          ]
          and
          [
              _Ty=std::_Iterator_base12 *
          ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\utility(655,42): error C2440: '=': cannot convert from '_Other' to '_Ty'
          with
          [
              _Other=int
          ]
          and
          [
              _Ty=std::_Container_proxy *
          ]
`

please help, Thanks

**Comment by flanglet** [comment]
Hi,
I need for information to help you:
what version of C++ are you targeting ? Is it C++ 20 ? Did you get the VS solution from a release or the latest github ? Can you copy the complete log (the error you copied is not in Kanzi code).

**Comment by check4game** [comment]
Thanks
