### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [flanglet/kanzi-cpp#2]
Dear @flanglet,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by flanglet** [comment]
I attached an executable built on Windows with mingw. It requires the 3 DLLs at runtime.
I can generate an executable from Visual Strudio but I do not have recent versions of the compiler and the binary may not be fully optimized.

**Comment by sergeevabc** [comment]
@flanglet, I appreciate you responding so quickly!
VS binary is more portable, a single file, so it is preferred over anything else, no matter how optimized.

**Comment by flanglet** [comment]
I removed the mingw based executable and uploaded a msvc based one with no dependencies.

**Comment by sergeevabc** [comment]
@flanglet, I confirm that launch is possible on Windows 7, but am confused on how to use it.
Consider adding some “Quick start” section to the front page or at least to the wiki with a few basic commands.

**Comment by flanglet** [comment]
Will do.

**Comment by flanglet** [comment]
Updated the WIKI.
