### ISSUE TITLE
Directory as input

### ISSUE THREAD

**Issue by AR1415** [flanglet/kanzi-cpp#3]
the input option for a directory to compress to a single file seems to compress each file individually instead of all merged into one. is whole directory not supported?

**Comment by flanglet** [comment]
This is a design choice since it is possible to tar either the source directory before or the destination directory after compression.
EG: tar cf dir.tar dir && kanzi -c -i dir.tar -f -l <level>
EG: kanzi -c -i dir -o out -f -l <level> && tar cf out.tar out

**Comment by AR1415** [comment]
it appears an error:

Warning: ignoring unknown option [tar]
Warning: ignoring unknown option [cf]

**Comment by flanglet** [comment]
Are you on Windows ? Otherwise tar is a commonly available tool.

**Comment by AR1415** [comment]
oh yes i am on the Windows operating system perhaps this is why

**Comment by AR1415** [comment]
ah i nearly have it, i get a small error come back saying dir.tar cannot access input

**Comment by flanglet** [comment]
Try line by line
tar cf <dir_name>.tar <dir_name>
kanzi -c -i <dir_name>.tar -f -l <level>

**Comment by AR1415** [comment]
im still receiving the error "Cannot access input file 'dir.tar'. Error code: 10"

**Comment by flanglet** [comment]
It means the compressor cannot find the file 'dir.tar'. Did you call it differently ? Did you change directories ? Did the first command succeed ? What does "dir dir.tar" return ?

**Comment by AR1415** [comment]
the first command making the dir.tar file with the files in it works fine, i can see the files with 7z. but the command with kanzi kicks back that it cant access the input file when it is sitting next to it

**Comment by flanglet** [comment]
What does "dir dir.tar" return ? What are your exact command lines ?

**Comment by AR1415** [comment]
tar cf dir.tar "D:\Hearthstone" && Kanzi64.exe -c -i dir.tar -f -b 1g -l 9

**Comment by flanglet** [comment]
OK. Then if you type simply "Kanzi64.exe -c -i dir.tar -f -b 1g -l 9", you get the error ?
What is the size of dir.tar ?

**Comment by AR1415** [comment]
yes typing in just that kanzi command has the error. the tar file is fine its 5GB as the source size is originally

**Comment by flanglet** [comment]
There may be a problem with files over 4GB on Windows. I do not have such a file to test. I will look into this.

**Comment by flanglet** [comment]
I uploaded a mingw based Windows executable in a zip asset attached to the release. Can you try it ?

**Comment by AR1415** [comment]
i have tested with another folder of 3.5GB issue still persists. But less than 2GB input works.

**Comment by flanglet** [comment]
I uploaded a new Kanzi64.exe. Give a try and let me know.

**Comment by AR1415** [comment]
error still occurs

**Comment by AR1415** [comment]
sorry i meant there is a different error that says "The input and output files must be different"

**Comment by AR1415** [comment]
oh i downloaded the wrong one, the new one uploaded seems to work now
