### ISSUE TITLE
Add brunsli JPEG compressor as a transform

### ISSUE THREAD

**Issue by M-Gonzalo** [flanglet/kanzi-cpp#4]
Hi Frederic! Do you think it might be possible for you to add a new transform for jpg files using brunsli? Especially if it can detect them inside compounded data, like a tar archive.

I'm available for testing! BTW, reporting that kanzi is working flawlessly on ARM aarch64, compiled with clang 👍👌

**Comment by flanglet** [comment]
I see where you are going with this. Discarding the entropy part to just use the tranforms with another entropy codec is not my plan. I would rather improve the entropy stage if needed. Also, I would consider adding these kinds of prefilters when I convince myself to build an archiver on top of this compressor (maybe next year). It would fit better in that context.

**Comment by M-Gonzalo** [comment]
Yes, I understand what you mean and I agree. Perhaps I didn't explain myself clearly. I'm not advocating for striping the entropy coding from anything, just compressing the file/stream with an external library (and its entropy coder if it has one), and pass that along. Doesn't really matter if there's some more entropy coding afterwards in the tool chain, as it will happen anyway if the final codec tries to compress a JPG image, or most multimedia for that matter.

**Comment by flanglet** [comment]
I understand your POV but I will close this. I do not want to add this kind of dependency in the compressor (it would be hard to maintain consistency with the Java & Go implementations). I also do not want kanzi to turn into a pre-processor for other compressors. Once I start work on an archiver (only C++), then I am open to adding these pre-processing tools.
