### ISSUE TITLE
Cannot access input file 'stdin', when decompressing

### ISSUE THREAD

**Issue by twekkel** [flanglet/kanzi-cpp#6]
$ echo hello | kanzi -c -i stdin -o stdout > hello.knz
$ kanzi -d -i hello.knz -o stdout
hello

$ cat hello.knz | kanzi -d -i stdin -o stdout
Cannot access input file 'stdin'. Error code: 10

**Comment by flanglet** [comment]
I pushed a fix. Can you give it a try ?
