### ISSUE TITLE
Blocksize integer overflow

### ISSUE THREAD

**Issue by twekkel** [flanglet/kanzi-cpp#7]
While 1G is the maximum documented blocksize...

$ echo "Block size" | kanzi -c -i stdin -t rolzx -b 1G -o stdout > block
$ echo "Block size" | kanzi -c -i stdin -t rolzx -b 2G -o stdout > block
Could not create the compressor: Minimum block size is 1 KB (1024 bytes), got -2147483648 bytes
$ echo "Block size" | kanzi -c -i stdin -t rolzx -b 3G -o stdout > block
Could not create the compressor: Minimum block size is 1 KB (1024 bytes), got -1073741824 bytes
$ echo "Block size" | kanzi -c -i stdin -t rolzx -b 4G -o stdout > block
Could not create the compressor: Minimum block size is 1 KB (1024 bytes), got 0 bytes
$ echo "Block size" | kanzi -c -i stdin -t rolzx -b 5G -o stdout > block

sorry it is again not a compression related bug ;)

**Comment by flanglet** [comment]
Thanks for reporting this issue. I will push a fix shortly.
Frankly, I'd better fix such minor issues like these than complex and critical corner cases in multi-threaded (de)compression scenarios.

**Comment by flanglet** [comment]
Commit [b057b98]
