### ISSUE TITLE
Empty file compression

### ISSUE THREAD

**Issue by twekkel** [flanglet/kanzi-cpp#8]
Again not a big issue, but if there is "nothing to do" the output file "test.knz" should probably not be created.

$ touch test
$ ./kanzi -c -i test

Kanzi 2.0 (c) Frederic Langlet

1 file to compress

Input file test is empty ... nothing to do
$ ./kanzi -d -i test.knz -o stdout
Invalid stream type. Error code: 15

**Comment by flanglet** [comment]
Commit [23a503a]
