### ISSUE TITLE
Block size too big?

### ISSUE THREAD

**Issue by twekkel** [flanglet/kanzi-cpp#9]
Same 252K file with random bytes. Since block size is way bigger than the file size, it shouldn't matter, at least I would thing so.

blocksize 15m compression time < 1s
blocksize 16m compression time > 160s

This is on a vm which "only" 700MB of memory and I can not reproduce on a 8GB linux machine.

$ ./kanzi -c -l 9 -b 15m -i in -f

Kanzi 2.0 (c) Frederic Langlet

1 file to compress

Compressing in: 257514 => 258387 (100.34%) in 998 ms
$ ./kanzi -c -l 9 -b 16m -i in -f

Kanzi 2.0 (c) Frederic Langlet

1 file to compress

Compressing in: 257514 => 258387 (100.34%) in 160.8 s

**Comment by flanglet** [comment]
It looks like an issue with the VM. 
On my laptop, using /usr/bin/time -v and an input file of size 458795, I get
/usr/bin/time -v ../bin/kanzi -c -i ~/Downloads/mesh-pldi19-powers.pdf -b 15m -f -e tpaqx
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.58
Maximum resident set size (kbytes): 404636
/usr/bin/time -v ../bin/kanzi -c -i ~/Downloads/mesh-pldi19-powers.pdf -b 16m -f -e tpaqx
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.73
Maximum resident set size (kbytes): 667964

So, no visible difference in terms of speed.
The most likely scenario is that the size of resident memory for the 16m block compression forces the machine to swap to disk which can be really slow on VMs.

As an aside, trying to compress a file with random data is the worst case scenario in terms of speed.

**Comment by twekkel** [comment]
Don't see swap being used, but VMs can indeed tell kinds of things... while doing something else. Issue can be closed, as I can not even reproduce it on a "normal" machine.

My understanding of block size seems wrong, has nothing to do with input size... but all with memory allocation?

**Comment by flanglet** [comment]
Same, I cannot see this behavior as well on my machine.
The block size controls the amount of memory used (and the compression ratio) since the input is broken input blocks of the provided size before being processed block by block (or block in parallel). TPAQ(X) also uses it as a hint to allocate more memory and improve compression when the block size is bigger than the input size.
